# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm

    mappings:
        profile_images:
            uri_prefix: /uploads/profile_images
            upload_destination: '%kernel.project_dir%/public/uploads/profile_images'
