#index:
#    path: /
#    controller: App\Controller\DefaultController::index
send_test_email:
  path: '/send-test-email'
  controller: 'App\Controller\TestController::sendTestEmail'
# config/routes.yaml


