#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_statistic_resources_per_terrain:
  path: '/statistic/resources-per-terrain'
  controller: 'App\Controller\StatisticController::resourcesPerTerrain'
  methods: ['GET']

app_activite_statistics:
  path: '/statistics'
  controller: 'App\Controller\ActiviteController::statistics'

app_activite_show_statistics:
  path: '/show-statistics'
  controller: 'App\Controller\ActiviteController::showStatistics'

# config/routes.yaml

app_terrain_qr_code:
  path: '/{idterrain}/qr-code'
  controller: 'App\Controller\TerrainController::generateQrCode'
  methods: ['GET']
  format: json

