#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

app_transaction_search:
    path: /search
    controller: 'App\Controller\TransactionController::search'
app_transaction_calculer_difference:
    path: /calculer-difference
    controller: 'App\Controller\TransactionController::calculerDifference'

